apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-gin-api-chart.fullname" . }}-secrets
type: Opaque
data:
  GIN_MODE: {{ .Values.AppSettings.GIN_MODE | b64enc | quote }}
  PORT: {{ .Values.AppSettings.PORT | b64enc | quote }}
